version: '3.2'
services:
  db:
    build:
      context: .
      dockerfile: mysql_docker_env/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - .utilities/shared_docker_volume/mysql_db/:/var/lib/mysql
# Names our volume
volumes:
  my-db: